# Developed by Eng Mouaz M Shahmeh 2022
name: bosra_elcham
description: Developed by Eng Mouaz M Shahmeh
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.14.0
  cloud_firestore: ^3.1.11
  firebase_auth: ^3.3.13
  firebase_storage: ^10.2.11
  provider: ^6.0.2
  go_router: ^3.0.7
  intl: ^0.17.0
  animated_text_kit: ^4.2.1
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai.ttf
